### ISSUE TITLE
Javascript: Refactor existing tests using child processes

### ISSUE THREAD

**Issue by lechlm** [se2p/ps-wise-2021-public-tests#14]
The javascript version of minesweeper is currently tested by calling the main() method inside each test, which prevents using the process.exit() functionality inside minesweeper. Furthermore, different handling of the input arguments is required depending on whether the main is executed inside a test case or the command line is used to execute the program (cf. https://github.com/se2p/ps-wise-2021-program-description/issues/14).

To address this issue, the existing tests should be refactored to spawn a child process, which then runs minesweeper (similar to pull request #10 ).

**Comment by alessiogambi** [comment]
Now I need to fix the private tests as well, then we can close this issue

**Comment by alessiogambi** [comment]
Done
