### ISSUE TITLE
Add *sh to gitignore file

### ISSUE THREAD

**Issue by patrickkatzer** [se2p/ps-wise-2021-public-tests#28]
Is it possible to add *sh to the gitignore file?

I have some shell scripts for my workflow with the WSL and I don't want to have them uploaded to the repository. So first thing I always do on a new assignment is to add *sh to the gitignore.

Maybe you can do this by default.

Thanks!

**Comment by alessiogambi** [comment]
Done for assignments 03, 04 and 05
