### ISSUE TITLE
package-lock.json gets changed

### ISSUE THREAD

**Issue by fatadel** [se2p/ps-wise-2021-public-tests#32]
When I initially set up an assignment project and run `make test`, my `package-lock.json` gets changed.
And then every time I run `git status` I get a message that I have uncommitted changes in my `public-tests` submodule, which pretty annoying.
Does it happen only with my setup?
If it's not only my issue, could we please refine our usage of `package-lock.json` file, @alessiogambi?

**Comment by alessiogambi** [comment]
@fatadel can you try this solution:

https://medicineyeh.wordpress.com/2015/07/15/how-to-ignore-changes-in-git-submodules/

**Comment by fatadel** [comment]
@alessiogambi 
It works, thank you!
